version: '3.8'

services:

  db:
    container_name: mysql_container
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: P@ssw0rd@admin
    ports:
      - "3306:3306"

  phpmyadmin:
    container_name: phpmyadmin-container
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
